spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  jackson:
    property-naming-strategy: SNAKE_CASE
